name: Jeff G. Peters
favicon: null
layout_spectrum: 0.09449764434248209
typography_spectrum: 0.7543409706559032
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9623250551521778
  lightness: 0.5154027075041085
  saturation: 0.10158054996281862
  rhythmicContrast: 0.27410431602038443
purpose: []
